<?php
/**
 * @var $block \PeterBrain\TermsConditions\Block\Widget\Tc
 */
?>
<?php if ($block->isEnabled()): ?>

    <?php
    $agreementId = $block->getAgreementId();
    $agreement = $block->getAgreementById($agreementId);
    ?>
    <?php if ($agreement): ?>
        <div class="terms-conditions-<?= (int) $agreementId; ?>">
            <?php if ($block->agreementIsHtml($agreementId)): ?>
                <?= /* @noEscape */ $block->getAgreementById($agreementId); ?>
            <?php else: ?>
                <?= $block->escapeHtml(nl2br($block->getAgreementById($agreementId)), ['br']); ?>
            <?php endif; ?>
        </div>
    <?php endif; ?>

<?php endif; ?>
