<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 */
?>
<?php $agreements = $block->getData('agreements'); ?>
<?php if ($agreements && count($agreements) > 0): ?>
    <ol class="agreements items">
        <?php foreach ($agreements as $agreement): ?>
            <li class="item">
                <?php if ($agreement->getIsHtml()): ?>
                    <?= /* @noEscape */ $agreement->getContent(); ?>
                <?php else: ?>
                    <?= $block->escapeHtml(nl2br($agreement->getContent()), ['br']); ?>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ol>
<?php else: ?>
    <p><?= /* @noEscape */ __("There are no terms and conditions configured yet."); ?></p>
<?php endif; ?>
